version: '3'
services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "80:8080"
    environment:
      - SWAGGER_JSON=/var/swagger/openapi.json
    volumes:
      - ../gen/http:/var/swagger

